# Generated by Django 4.2.21 on 2025-06-26 15:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusAccount',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.PositiveIntegerField(default=0, help_text='Current bonus balance', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Balance')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the bonus account is active', verbose_name='Is active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bonus_account', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Bonus account',
                'verbose_name_plural': 'Bonus accounts',
                'ordering': ('-modified',),
                'indexes': [models.Index(fields=['user'], name='bonuses_bon_user_id_712644_idx'), models.Index(fields=['is_active'], name='bonuses_bon_is_acti_57c3f0_idx')],
            },
        ),
    ]
