# Generated by Django 4.2.21 on 2025-06-26 15:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonuses', '0001_add_bonus_account_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusTransaction',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(help_text='Amount of bonuses (positive for earning, negative for spending)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Amount')),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent'), ('admin_earned', 'Admin earned'), ('admin_spent', 'Admin spent')], max_length=32, verbose_name='Transaction type')),
                ('reason', models.CharField(blank=True, help_text='Description of the transaction', max_length=512, verbose_name='Reason')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='bonuses.bonusaccount', verbose_name='Bonus account')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this transaction (for admin operations)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bonus_transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Bonus transaction',
                'verbose_name_plural': 'Bonus transactions',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['account', '-created'], name='bonuses_bon_account_42548f_idx'), models.Index(fields=['transaction_type'], name='bonuses_bon_transac_69a3c2_idx')],
            },
        ),
    ]
