# Generated by Django 4.2.21 on 2025-06-27 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0002_add_bonus_transaction_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonustransaction',
            options={'ordering': ('-created',), 'permissions': [('allow_bonuses_integration', 'Can send requests from the shop for user bonuses integration')], 'verbose_name': 'Bonus transaction', 'verbose_name_plural': 'Bonus transactions'},
        ),
    ]
