# Generated by Django 4.2.21 on 2025-07-02 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0003_add_permissions_to_bonus_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonustransaction',
            name='amount',
            field=models.IntegerField(help_text='Amount of bonuses (always positive)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Amount'),
        ),
    ]
