# Generated by Django 4.2.21 on 2025-07-28 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonuses', '0004_update_amount_for_bonus_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusaccount',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_account', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='bonustransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bonuses.bonusaccount', verbose_name='Bonus account'),
        ),
    ]
