# Generated by Django 4.2.21 on 2025-07-28 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonuses', '0005_set_user_fk_nullable_to_bonus_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonustransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this transaction (for admin operations)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
