# Generated by Django 4.2.21 on 2025-07-28 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_add_lifetime_to_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_add_payment_and_recurrent_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product purchased with this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who made this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='recurrent',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product for which the recurring subscription is enabled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrent_subscriptions', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='recurrent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrent_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
