# Generated by Django 4.2.21 on 2025-07-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_add_lifetime_to_product'),
        ('payments', '0002_set_user_and_product_fk_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product purchased with this payment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='recurrent',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product for which the recurring subscription is enabled.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurrent_subscriptions', to='products.product', verbose_name='Product'),
        ),
    ]
