# Generated by Django 4.2.21 on 2025-07-31 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_set_product_fk_protect'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInstrument',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('DOLYAME', 'Dolyame'), ('SPLIT', 'Split'), ('STRIPE', 'Stripe'), ('TINKOFF', 'Tinkoff'), ('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay')], db_index=True, help_text='Payment provider (Tinkoff, Stripe, etc.).', max_length=16, verbose_name='Provider')),
                ('payment_method', models.CharField(choices=[('CARD', 'Bank card'), ('CARD_RECURRENT', 'Bank card (recurrent)'), ('SBP', 'SBP (Fast Payments)'), ('SBP_RECURRENT', 'SBP (Fast Payments, recurrent)'), ('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay')], db_index=True, help_text='Method used for payment (card, sbp, apple pay, etc.).', max_length=24, verbose_name='Payment method')),
                ('card_mask', models.CharField(help_text='Masked card number (e.g. ****7382).', max_length=24, verbose_name='Card mask')),
                ('exp_date', models.CharField(help_text='Card expiration date in MMYY format (e.g. 0925).', max_length=6, verbose_name='Expiry date')),
                ('card_id', models.CharField(blank=True, default='', help_text='Optional card ID from provider (used for some providers).', max_length=64, verbose_name='Card ID')),
                ('rebill_id', models.CharField(blank=True, db_index=True, default='', help_text='Rebill ID used to initiate recurring charges.', max_length=64, verbose_name='Rebill ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', help_text='Current status of the payment instrument.', max_length=16, verbose_name='Status')),
                ('token', models.CharField(blank=True, default='', help_text='Optional provider token (not used for payment, but may be useful for unsubscribing, deleting or managing the card).', max_length=512, verbose_name='Card token')),
            ],
            options={
                'verbose_name': 'Payment instrument',
                'verbose_name_plural': 'Payment instruments',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveIndex(
            model_name='recurrent',
            name='payments_re_charge__c780ea_idx',
        ),
        migrations.RemoveField(
            model_name='recurrent',
            name='attempts_charge',
        ),
        migrations.RemoveField(
            model_name='recurrent',
            name='charge_method',
        ),
        migrations.RemoveField(
            model_name='recurrent',
            name='charge_token',
        ),
        migrations.RemoveField(
            model_name='recurrent',
            name='provider',
        ),
        migrations.AddField(
            model_name='paymentinstrument',
            name='user',
            field=models.ForeignKey(help_text='User who owns this payment instrument.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_instruments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_instrument',
            field=models.ForeignKey(blank=True, help_text='Instrument used for this payment (card, sbp, etc).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.paymentinstrument', verbose_name='Payment instrument'),
        ),
        migrations.AddField(
            model_name='recurrent',
            name='payment_instrument',
            field=models.ForeignKey(blank=True, help_text='Payment instrument used for recurring charges.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrent_subscriptions', to='payments.paymentinstrument', verbose_name='Payment instrument'),
        ),
        migrations.AddIndex(
            model_name='paymentinstrument',
            index=models.Index(fields=['user', 'provider', 'rebill_id'], name='payments_pa_user_id_5de73a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinstrument',
            index=models.Index(fields=['status'], name='payments_pa_status_4b17b2_idx'),
        ),
    ]
