# Generated by Django 4.2.21 on 2025-07-31 18:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_changing_for_payment_recurrent_payment_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrentChargeAttempt',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAIL', 'Fail')], db_index=True, help_text='Result of this charge attempt.', max_length=8, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount attempted to be charged.', max_digits=10, verbose_name='Attempted charge amount')),
                ('error_code', models.CharField(blank=True, default='', help_text='Optional error code returned by the payment provider.', max_length=64, verbose_name='Error code')),
                ('error_message', models.TextField(blank=True, default='', help_text='Detailed error message from provider, if any.', verbose_name='Error message')),
                ('external_payment_id', models.CharField(blank=True, default='', help_text='ID of the payment in external system (if available).', max_length=128, verbose_name='External payment ID')),
                ('provider_response', models.JSONField(blank=True, help_text='Raw response from the payment provider.', null=True, verbose_name='Provider response')),
                ('payment', models.ForeignKey(blank=True, help_text='Linked payment if the charge was successful.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_attempts', to='payments.payment', verbose_name='Payment')),
                ('recurrent', models.ForeignKey(help_text='Recurring subscription for which this charge attempt was made.', on_delete=django.db.models.deletion.CASCADE, related_name='charge_attempts', to='payments.recurrent', verbose_name='Recurrent')),
            ],
            options={
                'verbose_name': 'Recurrent charge attempt',
                'verbose_name_plural': 'Recurrent charge attempts',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['recurrent', 'status'], name='payments_re_recurre_f8736d_idx'), models.Index(fields=['payment'], name='payments_re_payment_e0d9fb_idx')],
            },
        ),
    ]
