# Generated by Django 4.2.21 on 2025-08-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_recurrent_charge_attempt_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrentchargeattempt',
            name='currency',
            field=models.CharField(blank=True, default='', help_text='Currency of the attempted charge.', max_length=8, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='paymentinstrument',
            name='exp_date',
            field=models.CharField(blank=True, default='', help_text='Card expiration date in MMYY format (e.g. 0925).', max_length=6, verbose_name='Expiry date'),
        ),
    ]
