# Generated by Django 4.2.21 on 2025-08-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_add_currency_to_recurrent_charge_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinstrument',
            name='card_mask',
            field=models.CharField(blank=True, default='', help_text='Masked card number (e.g. ****7382).', max_length=24, verbose_name='Card mask'),
        ),
    ]
