# Generated by Django 4.2.21 on 2025-08-04 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_add_lifetime_to_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0007_alter_payment_instrument_card_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrent',
            name='product',
            field=models.ForeignKey(help_text='Product for which the recurring subscription is enabled.', on_delete=django.db.models.deletion.PROTECT, related_name='recurrent_subscriptions', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='recurrent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrent_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
