---
- name: Add docker.com GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker.com apt repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable

- name: Install required packages
  ansible.builtin.apt:
    name:
      - docker-ce=5:27.3.1-1~ubuntu.24.04~noble
      - docker-compose
      - python3-pip
      - python3-jsondiff

- name: Make sure docker python module is installed
  ansible.builtin.pip:
    name: docker
    break_system_packages: true
