# Generated by Django 4.2.16 on 2024-11-15 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopDeadLetter",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(db_index=True, max_length=32)),
                ("raw_data", models.JSONField(default=dict)),
                ("details", models.TextField(blank=True, default="", help_text="Error details")),
            ],
            options={
                "verbose_name": "Shop dead letter",
                "verbose_name_plural": "Shop dead letters",
                "ordering": ["created"],
            },
        ),
    ]
