# Generated by Django 4.2.16 on 2024-11-18 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a12n", "0001_email_auth_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passwordlessemailauthcode",
            options={"verbose_name": "Passwordless email auth code", "verbose_name_plural": "Passwordless email auth codes"},
        ),
    ]
