---
name: CI
on:  # yamllint disable-line
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version-file: '.python-version'

      - uses: actions/cache@v4
        id: deps-cache
        with:
          path: |
            venv
            ~/.ansible
            ./.cache
          key: v1-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.yml') }}

      - name: Install dependencies
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          ansible-galaxy install -r requirements.yml

      - name: Restore ansible vault password
        run: echo ${{ secrets.ANSIBLE_VAULT_KEY }} > .vault-key

      - name: Run the lint
        run: |
          . venv/bin/activate
          make lint

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version-file: '.python-version'

      - uses: actions/cache/restore@v4
        id: deps-cache
        with:
          path: |
            venv
            ~/.ansible
            ./.cache
          key: v1-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.yml') }}
          fail-on-cache-miss: true

      - name: Restore ansible vault password
        run: echo ${{ secrets.ANSIBLE_VAULT_KEY }} > .vault-key

      - name: Install ssh keys
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Run the playbook
        run: |
          . venv/bin/activate
          ansible-playbook site.yml -i hosts -u infra -b
