# Generated by Django 4.2.16 on 2024-11-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_email_confirmation_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": [("allow_mindbox_integration", "Can send integration requests from the mindbox")]},
        ),
    ]
