# Generated by Django 4.2.16 on 2024-11-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_mindbox_integration_permission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("allow_mindbox_integration", "Can send integration requests from the mindbox")],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="email_confirmed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Email confirmed at"),
        ),
    ]
