# Generated by Django 4.2.16 on 2024-11-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_verbose_name_for_l12n"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_slug",
            field=models.SlugField(
                blank=True,
                choices=[
                    ("abstract", "abstract"),
                    ("apollo", "apollo"),
                    ("caravaggio", "caravaggio"),
                    ("cat", "cat"),
                    ("frida", "frida"),
                    ("indian", "indian"),
                    ("joker", "joker"),
                    ("lakoon", "lakoon"),
                    ("medieval", "medieval"),
                    ("thinker", "thinker"),
                    ("venus", "venus"),
                    ("woman", "woman"),
                ],
                verbose_name="Avatar slug",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birthdate",
            field=models.DateField(blank=True, null=True, verbose_name="Birthdate"),
        ),
    ]
