# Generated by Django 4.2.17 on 2025-02-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_avatar_birthdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rhash",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Rhash"
            ),
        ),
    ]
