# Generated by Django 4.2.17 on 2025-02-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_redirect_to_beta_synchronize_fields"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("rhash", ""), _negated=True),
                fields=("rhash",),
                name="unique_rhash",
            ),
        ),
    ]
