# Generated by Django 4.2.17 on 2025-02-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_unique_rhash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rhash",
            field=models.CharField(blank=True, max_length=256, verbose_name="Rhash"),
        ),
    ]
