# Generated by Django 4.2.17 on 2025-02-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_biger_rhash"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_rhash",
        ),
    ]
