# Generated by Django 4.2.21 on 2025-07-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_add_cover_to_category'),
        ('users', '0009_drop_unique_rhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='all_interests',
            field=models.BooleanField(default=False, help_text='Whether the user has selected all interests', verbose_name='All interests selected'),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, help_text="User's selected interests", related_name='users', to='courses.category', verbose_name='Interests'),
        ),
    ]
