# Generated by Django 4.2.21 on 2025-07-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_update_avatar_slug_for_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_slug',
            field=models.SlugField(blank=True, choices=[('abstract', 'abstract'), ('apollo', 'apollo'), ('caravaggio', 'caravaggio'), ('cat', 'cat'), ('cat2', 'cat2'), ('frida', 'frida'), ('indian', 'indian'), ('joker', 'joker'), ('lakoon', 'lakoon'), ('medieval', 'medieval'), ('rafael', 'rafael'), ('rossetti', 'rossetti'), ('thinker', 'thinker'), ('venus', 'venus'), ('venus2', 'venus2'), ('woman', 'woman')], verbose_name='Avatar slug'),
        ),
    ]
