# Generated by Django 4.2.21 on 2025-07-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_update_avatar_slug_for_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_accepted_data_consent',
            field=models.BooleanField(blank=True, help_text='Whether the user has accepted data consent in the App', null=True, verbose_name='Has accepted data consent in the App'),
        ),
    ]
