# Generated by Django 4.2.21 on 2025-08-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_has_accepted_data_consent_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', help_text="User's phone number", max_length=32, verbose_name='Phone'),
        ),
    ]
