# Generated by Django 4.2.16 on 2024-11-05 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_init"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True, verbose_name="Name")),
                (
                    "product_type",
                    models.CharField(
                        choices=[("course", "Course"), ("course collection", "Course collection"), ("subscription", "Subscription")], verbose_name="Type"
                    ),
                ),
                ("external_id", models.CharField(max_length=128, unique=True, verbose_name="External ID")),
                (
                    "course_collections",
                    models.ManyToManyField(blank=True, related_name="products", to="courses.coursecollection", verbose_name="Course collections"),
                ),
                ("course_versions", models.ManyToManyField(blank=True, related_name="products", to="courses.courseversion", verbose_name="Course versions")),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["name"],
            },
        ),
    ]
