# Generated by Django 4.2.16 on 2024-11-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_init"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("course", "Course"), ("course-collection", "Course collection"), ("subscription", "Subscription")], verbose_name="Type"
            ),
        ),
    ]
