# Generated by Django 4.2.16 on 2024-12-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_better_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="external_id",
        ),
        migrations.AddField(
            model_name="product",
            name="shop_id",
            field=models.CharField(blank=True, max_length=128, verbose_name="Shop ID"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(condition=models.Q(("shop_id", ""), _negated=True), fields=("shop_id",), name="unique_or_empty_product_shop_id"),
        ),
    ]
