# Generated by Django 4.2.16 on 2024-12-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_shop_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Name"),
        ),
    ]
