# Generated by Django 4.2.16 on 2024-12-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0019_replace_course_collection_with_course_series"),
        ("products", "0004_product_name_not_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="course_collections",
        ),
        migrations.AddField(
            model_name="product",
            name="course_series",
            field=models.ManyToManyField(blank=True, related_name="products", to="courses.courseseries", verbose_name="Course series"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(choices=[("course", "Course"), ("course-series", "Course series"), ("subscription", "Subscription")], verbose_name="Type"),
        ),
    ]
