# Generated by Django 4.2.17 on 2024-12-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_replace_course_collection_with_course_series"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
    ]
