# Generated by Django 4.2.17 on 2025-01-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_longer_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("course", "Course"), ("course-series", "Course series"), ("subscription", "Subscription")], db_index=True, verbose_name="Type"
            ),
        ),
    ]
