# Generated by Django 4.2.17 on 2025-02-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_type_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="redirect_url",
            field=models.URLField(
                blank=True, max_length=255, verbose_name="Redirect URL"
            ),
        ),
    ]
