# Generated by Django 4.2.17 on 2025-02-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_redirect_to_beta_lms_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="redirect_url",
            field=models.URLField(
                blank=True, db_index=True, max_length=255, verbose_name="Redirect URL"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shop_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, verbose_name="Shop ID"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_type", "-created"],
                name="product_producttypecreated_idx",
            ),
        ),
    ]
