# Generated by Django 4.2.17 on 2025-02-12 05:40

from django.db import migrations, models
import django.db.models.deletion
import uuid



def fill_course_versions_plans(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    CourseVersionPlanProduct = apps.get_model('products', 'CourseVersionPlanProduct')
    CoursePlan = apps.get_model('courses', 'CoursePlan')

    for product in Product.objects.all():
        for course_version in product.course_versions.all():
            course_plan, _ = CoursePlan.objects.get_or_create(
                course_version=course_version,
                default_for_version=True,
                defaults={"name": "Основной план"},
            )
            CourseVersionPlanProduct.objects.create(
                product=product,
                course_version=course_version,
                course_plan=course_plan,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0046_create_default_course_plans"),
        ("products", "0009_add_extra_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseVersionPlanProduct",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "course_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.courseplan",
                    ),
                ),
                (
                    "course_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.courseversion",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="course_versions_plans",
            field=models.ManyToManyField(
                blank=True,
                related_name="products_with_plans",
                through="products.CourseVersionPlanProduct",
                to="courses.courseversion",
                verbose_name="Course versions plans",
            ),
        ),
        migrations.AddIndex(
            model_name="courseversionplanproduct",
            index=models.Index(
                fields=["product", "course_version", "course_plan"],
                name="products_co_product_c6ab64_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseversionplanproduct",
            constraint=models.UniqueConstraint(
                fields=("product", "course_version"),
                name="unique_product_course_version",
            ),
        ),
        migrations.RunPython(
            code=fill_course_versions_plans,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
