# Generated by Django 4.2.17 on 2025-02-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0046_create_default_course_plans"),
        ("products", "0010_add_course_plan_to_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseversionplanproduct",
            options={
                "default_related_name": "course_version_plans",
                "ordering": ["created"],
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="course_versions",
        ),
        migrations.AlterField(
            model_name="product",
            name="course_versions_plans",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                through="products.CourseVersionPlanProduct",
                to="courses.courseversion",
                verbose_name="Course versions plans",
            ),
        ),
    ]
