# Generated by Django 4.2.21 on 2025-06-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_drop_old_m2m_to_versions_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='apple_product_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Apple product ID'),
        ),
    ]
