# Generated by Django 4.2.21 on 2025-07-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_add_apple_product_id_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lifetime',
            field=models.PositiveIntegerField(blank=True, help_text='How many days access is granted after purchase.', null=True, verbose_name='Lifetime (in days)'),
        ),
    ]
