# Generated by Django 4.2.16 on 2024-11-26 04:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0008_default_sorting_positions_stars_at_one"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainPageRecommendation",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position", models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name="Position")),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="courses.course", verbose_name="Course")),
                (
                    "course_collection",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="courses.coursecollection", verbose_name="CourseCollection"
                    ),
                ),
            ],
            options={
                "verbose_name": "Main page recommendation",
                "verbose_name_plural": "Main page recommendations",
                "ordering": ["position"],
                "default_related_name": "main_page_recommendations",
            },
        ),
    ]
