# Generated by Django 4.2.16 on 2024-12-03 02:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0001_add_main_page_recommendations"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainPageContent",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("main_page_content_type", models.CharField(choices=[("lecturerscontent", "Lecturers"), ("categoriescontent", "Categories")], max_length=50, verbose_name="Main page content type")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("position_on_page", models.PositiveSmallIntegerField(default=1, verbose_name="Position on the main page")),
                ("is_hidden", models.BooleanField(default=True, verbose_name="Is hidden")),
            ],
            options={
                "verbose_name": "Main page content item",
                "verbose_name_plural": "Main page content items",
                "ordering": ["position_on_page", "created"],
            },
        ),
        migrations.CreateModel(
            name="CategoriesContent",
            fields=[
                (
                    "main_page_content",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="main_page.mainpagecontent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categories content item",
                "verbose_name_plural": "Categories content list",
                "ordering": ["position_on_page", "created"],
            },
            bases=("main_page.mainpagecontent", models.Model),
        ),
        migrations.CreateModel(
            name="LecturersContent",
            fields=[
                (
                    "main_page_content",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="main_page.mainpagecontent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lecturers content item",
                "verbose_name_plural": "Lecturers content list",
                "ordering": ["position_on_page", "created"],
            },
            bases=("main_page.mainpagecontent", models.Model),
        ),
        migrations.AddIndex(
            model_name="mainpagecontent",
            index=models.Index(fields=["position_on_page", "created"], name="main_page_m_positio_5ce26e_idx"),
        ),
        migrations.AddIndex(
            model_name="mainpagecontent",
            index=models.Index(fields=["position_on_page"], name="main_page_m_positio_70f115_idx"),
        ),
    ]
