# Generated by Django 4.2.16 on 2024-12-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0003_add_bundles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpagecontent",
            name="main_page_content_type",
            field=models.CharField(
                choices=[
                    ("lecturerscontent", "Lecturers"),
                    ("categoriescontent", "Categories"),
                    ("lessonbundlecontent", "Lessons bundle"),
                    ("coursebundlecontent", "Courses bundle"),
                ],
                max_length=50,
                verbose_name="Main page content type",
            ),
        ),
    ]
