# Generated by Django 4.2.16 on 2024-12-10 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0004_add_bundles_as_labeled_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainpagerecommendation",
            name="course_collection",
        ),
    ]
