# Generated by Django 4.2.16 on 2024-12-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0005_drop_course_collection_from_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpagecontent",
            name="pretitle_color",
            field=models.CharField(
                blank=True,
                choices=[("yellow", "yellow"), ("peach", "peach"), ("light-green", "light-green"), ("lilac", "lilac"), ("pink", "pink")],
                max_length=20,
                verbose_name="Pretitle color",
            ),
        ),
        migrations.AddField(
            model_name="mainpagecontent",
            name="pretitle_icon",
            field=models.CharField(
                blank=True,
                choices=[("lightning", "lightning"), ("flame", "flame"), ("heart", "heart"), ("star", "star"), ("note", "note")],
                max_length=20,
                verbose_name="Pretitle icon",
            ),
        ),
        migrations.AddField(
            model_name="mainpagecontent",
            name="pretitle_text",
            field=models.CharField(blank=True, max_length=20, verbose_name="Pretitle text"),
        ),
        migrations.AddConstraint(
            model_name="mainpagecontent",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("pretitle_color", ""), ("pretitle_icon", ""), ("pretitle_text", "")),
                    models.Q(
                        models.Q(("pretitle_text", ""), _negated=True),
                        models.Q(("pretitle_icon", ""), _negated=True),
                        models.Q(("pretitle_color", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="pretitle_fields_must_be_filled_together",
            ),
        ),
    ]
