# Generated by Django 4.2.16 on 2024-12-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0006_add_pretitle_fields_to_bundles"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mainpagecontent",
            name="pretitle_fields_must_be_filled_together",
        ),
        migrations.RemoveField(
            model_name="mainpagecontent",
            name="pretitle_color",
        ),
        migrations.RemoveField(
            model_name="mainpagecontent",
            name="pretitle_icon",
        ),
        migrations.RemoveField(
            model_name="mainpagecontent",
            name="pretitle_text",
        ),
        migrations.AddField(
            model_name="mainpagecontent",
            name="badge_color",
            field=models.CharField(
                blank=True,
                choices=[("yellow", "yellow"), ("peach", "peach"), ("light-green", "light-green"), ("lilac", "lilac"), ("pink", "pink")],
                max_length=20,
                verbose_name="Badge color",
            ),
        ),
        migrations.AddField(
            model_name="mainpagecontent",
            name="badge_icon",
            field=models.CharField(
                blank=True,
                choices=[("lightning", "lightning"), ("flame", "flame"), ("heart", "heart"), ("star", "star"), ("note", "note")],
                max_length=20,
                verbose_name="Badge icon",
            ),
        ),
        migrations.AddField(
            model_name="mainpagecontent",
            name="badge_text",
            field=models.CharField(blank=True, max_length=20, verbose_name="Badge text"),
        ),
        migrations.AddConstraint(
            model_name="mainpagecontent",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("badge_color", ""), ("badge_icon", ""), ("badge_text", "")),
                    models.Q(
                        models.Q(("badge_text", ""), _negated=True), models.Q(("badge_icon", ""), _negated=True), models.Q(("badge_color", ""), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="badge_fields_must_be_filled_together",
            ),
        ),
    ]
