# Generated by Django 4.2.16 on 2024-12-17 06:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_replace_lesson_with_lecture"),
        ("main_page", "0007_rename_pretitle_to_badge"),
    ]

    operations = [
        migrations.CreateModel(
            name="LectureBundleContent",
            fields=[
                (
                    "main_page_content",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="main_page.mainpagecontent",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Lecture bundle content item",
                "verbose_name_plural": "Lecture bundle content list",
                "ordering": ["position_on_page", "created"],
            },
            bases=("main_page.mainpagecontent", models.Model),
        ),
        migrations.CreateModel(
            name="LectureBundleItem",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position_in_lecture_bundle", models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name="Position in lectures bundle")),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="main_page.lecturebundlecontent", verbose_name="Lecture bundle"
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="lecture_bundle_items", to="courses.lecture", verbose_name="Lecture"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lecture bundle item",
                "verbose_name_plural": "Lecture bundle items",
                "ordering": ["position_in_lecture_bundle"],
            },
        ),
        migrations.RemoveField(
            model_name="lessonbundleitem",
            name="bundle",
        ),
        migrations.RemoveField(
            model_name="lessonbundleitem",
            name="lesson",
        ),
        migrations.AlterField(
            model_name="coursebundleitem",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lecture_bundle_items",
                to="courses.course",
                verbose_name="Course",
            ),
        ),
        migrations.AlterField(
            model_name="coursebundleitem",
            name="course_collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lecture_bundle_items",
                to="courses.coursecollection",
                verbose_name="Course collection",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagecontent",
            name="main_page_content_type",
            field=models.CharField(
                choices=[
                    ("lecturerscontent", "Lecturers"),
                    ("categoriescontent", "Categories"),
                    ("lecturebundlecontent", "Lectures bundle"),
                    ("coursebundlecontent", "Courses bundle"),
                ],
                max_length=50,
                verbose_name="Main page content type",
            ),
        ),
        migrations.DeleteModel(
            name="LessonBundleContent",
        ),
        migrations.DeleteModel(
            name="LessonBundleItem",
        ),
        migrations.AddConstraint(
            model_name="lecturebundleitem",
            constraint=models.UniqueConstraint(fields=("bundle", "lecture"), name="unique_lecture_per_bundle"),
        ),
    ]
