# Generated by Django 4.2.16 on 2024-12-17 08:07

from django.db import migrations, models
import django.db.models.deletion


def delete_course_bundle_items_with_null_course(apps, schema_editor):
    CourseBundleItem = apps.get_model('main_page', 'CourseBundleItem')
    CourseBundleItem.objects.filter(course__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0019_replace_course_collection_with_course_series"),
        ("main_page", "0008_replace_lesson_with_lecture"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="coursebundleitem",
            name="course_or_course_collection_specified",
        ),
        migrations.RemoveConstraint(
            model_name="coursebundleitem",
            name="unique_course_collection_per_bundle",
        ),
        # Add data migration to delete items with null course
        migrations.RunPython(
            delete_course_bundle_items_with_null_course,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="coursebundleitem",
            name="course_collection",
        ),
        migrations.AddField(
            model_name="coursebundleitem",
            name="course_series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lecture_bundle_items",
                to="courses.courseseries",
                verbose_name="Course series",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursebundleitem",
            constraint=models.CheckConstraint(
                check=models.Q(("course", None), ("course_series", None), _connector="XOR"),
                name="course_or_course_series_specified"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursebundleitem",
            constraint=models.UniqueConstraint(
                fields=("bundle", "course_series"),
                name="unique_course_series_per_bundle"
            ),
        ),
    ]
