# Generated by Django 4.2.17 on 2025-02-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0009_replace_course_collection_with_course_series"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpagecontent",
            name="is_hidden",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Is hidden"
            ),
        ),
    ]
