# Generated by Django 4.2.21 on 2025-07-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_add_cover_to_category'),
        ('main_page', '0010_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebundlecontent',
            name='personalization_categories',
            field=models.ManyToManyField(help_text='Select the categories that will personalize this bundle for users with matching interests.', related_name='course_bundles', to='courses.category', verbose_name='Personalization categories'),
        ),
    ]
