# Generated by Django 4.2.21 on 2025-07-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_add_cover_to_category'),
        ('main_page', '0012_add_personalization_categories_to_lecture_bundle_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebundlecontent',
            name='personalization_categories',
            field=models.ManyToManyField(blank=True, help_text='Select the categories that will personalize this bundle for users with matching interests.', related_name='course_bundles', to='courses.category', verbose_name='Personalization categories'),
        ),
        migrations.AlterField(
            model_name='lecturebundlecontent',
            name='personalization_categories',
            field=models.ManyToManyField(blank=True, help_text='Select the categories that will personalize this bundle for users with matching interests.', related_name='lecture_bundles', to='courses.category', verbose_name='Personalization categories'),
        ),
    ]
