---
- name: Make sure stack directory is present
  file:
    path: /srv/site
    state: directory

- name: Make sure internal networks are up
  community.docker.docker_network:
    name: "{{ item }}"
    driver: overlay
    # https://www.reddit.com/r/portainer/comments/qt1mne/swarm_deployment_woes/
    driver_options:
      com.docker.network.driver.mtu: 1450
  loop:
    - traefiknet

- name: Deploy the main site stack
  docker_stack:
    name: site
    resolve_image: never
    with_registry_auth: true
    compose:
      - version: "3.6"

        services:
          traefik:
            image: traefik:v3.3
            ports:
              - target: 80
                published: 80
                mode: host
              - target: 443
                published: 443
                mode: host

            deploy:
              mode: global
              placement:
                constraints:
                  - node.role == manager

            volumes:
              - /var/run/docker.sock:/var/run/docker.sock:ro
              - traefik-certificates:/certificates

            command:
              - --providers.swarm.endpoint=unix:///var/run/docker.sock
              - --providers.swarm.exposedByDefault=false

              - --entrypoints.web.address=:80
              - --entrypoints.web.http.redirections.entryPoint.to=websecure
              - --entrypoints.web.http.redirections.entryPoint.scheme=https
              - --entrypoints.websecure.address=:443

              - --certificatesresolvers.letsencrypt.acme.email=online@lms.com
              - --certificatesresolvers.letsencrypt.acme.storage=/certificates/acme.json
              - --certificatesresolvers.letsencrypt.acme.tlschallenge=true

              - --log.level=INFO
              - --accesslog
              - --log
            networks:
              - traefiknet

          periodic-prune:
            image: f213/periodic-docker-prune:1.1.1
            deploy:
              mode: global
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock

          log-streamer:
            image: gliderlabs/logspout:v3.2.14
            command: "syslog+tls://{{ papertrail_host }}:{{ papertrail_port }}"
            deploy:
              mode: global
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock

        networks:
          stacknet:
            driver: overlay
          traefiknet:
            external: true

        volumes:
          grafana_storage:
          traefik-certificates:
