# Generated by Django 4.2.16 on 2024-11-05 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_init"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAccess",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("start_date", models.DateField(verbose_name="Start date")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="End date")),
                ("order_id", models.CharField(db_index=True, max_length=128, verbose_name="Order ID")),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="access_items", to="products.product", verbose_name="Product"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="product_access_items", to=settings.AUTH_USER_MODEL, verbose_name="User"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product access",
                "verbose_name_plural": "Product access",
                "ordering": ["created"],
                "unique_together": {("product", "user", "start_date", "end_date")},
            },
        ),
    ]
