# Generated by Django 4.2.16 on 2024-11-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_access", "0001_init"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productaccess",
            name="order_id",
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name="Order ID"),
        ),
    ]
