# Generated by Django 4.2.16 on 2024-11-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_access", "0002_unique_product_access_order_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productaccess",
            options={
                "ordering": ["created"],
                "permissions": [("allow_shop_integration", "Can send integration requests from the shop")],
                "verbose_name": "Product access",
                "verbose_name_plural": "Product access",
            },
        ),
    ]
