# Generated by Django 4.2.16 on 2024-11-15 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0002_better_choices"),
        ("product_access", "0003_shop_integration_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="productaccess",
            name="granted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Granted at"),
        ),
        migrations.AddField(
            model_name="productaccess",
            name="revoked_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Revoked at"),
        ),
        migrations.AlterField(
            model_name="productaccess",
            name="product",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="access_items", to="products.product", verbose_name="Product"
            ),
        ),
        migrations.AlterField(
            model_name="productaccess",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_access_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
