# Generated by Django 4.2.16 on 2024-11-14 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_better_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product_access", "0004_product_access_grant_revoke_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productaccess",
            name="product",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="access_items", to="products.product", verbose_name="Product"
            ),
        ),
        migrations.AlterField(
            model_name="productaccess",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_access_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
