# Generated by Django 4.2.17 on 2025-01-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_access", "0005_product_access_nullable_user_product"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="productaccess",
            index=models.Index(fields=["revoked_at", "start_date", "end_date"], name="product_acc_revoked_c22268_idx"),
        ),
    ]
