# Generated by Django 4.2.17 on 2025-02-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_access", "0006_access_revoked_start_end_date_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productaccess",
            name="end_date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="End date"
            ),
        ),
        migrations.AlterField(
            model_name="productaccess",
            name="start_date",
            field=models.DateField(db_index=True, verbose_name="Start date"),
        ),
        migrations.AddIndex(
            model_name="productaccess",
            index=models.Index(
                fields=["revoked_at", "start_date", "end_date", "user"],
                name="product_acc_revoked_d95ba6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productaccess",
            index=models.Index(
                fields=["revoked_at", "start_date", "end_date", "user", "product"],
                name="product_acc_revoked_1c3fe4_idx",
            ),
        ),
    ]
