# Generated by Django 4.2.17 on 2025-02-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_access", "0007_add_more_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="productaccess",
            index=models.Index(
                fields=["user", "start_date", "end_date", "revoked_at"],
                name="product_acc_user_id_19883e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productaccess",
            index=models.Index(
                fields=["product", "user", "start_date", "end_date", "revoked_at"],
                name="product_acc_product_3d9865_idx",
            ),
        ),
    ]
