# Generated by Django 4.2.21 on 2025-07-28 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_access', '0008_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaccess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_access_items', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
