# Generated by Django 4.2.21 on 2025-08-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_access', '0009_set_user_fk_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaccess',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='productaccess',
            name='start_date',
            field=models.DateTimeField(db_index=True, verbose_name='Start date'),
        ),
    ]
