# Generated by Django 4.2.16 on 2024-11-04 04:15

import app.json_encoders
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MindboxOperationLog",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("operation", models.CharField(db_index=True, max_length=64, verbose_name="Mindbox operation name")),
                ("destination", models.CharField(db_index=True, max_length=512, verbose_name="Destination")),
                ("content", models.JSONField(encoder=app.json_encoders.AppJSONEncoder, verbose_name="Content")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
