# Generated by Django 4.2.16 on 2024-11-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindbox", "0001_init"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mindboxoperationlog",
            options={"verbose_name": "Mindbox operation log", "verbose_name_plural": "Mindbox operation log entries"},
        ),
    ]
