# Generated by Django 4.2.17 on 2025-02-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindbox", "0002_verbose_name_for_l12n"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mindboxoperationlog",
            name="destination",
            field=models.CharField(
                blank=True, db_index=True, max_length=512, verbose_name="Destination"
            ),
        ),
    ]
