# Generated by Django 4.2.21 on 2025-06-16 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mindbox', '0003_blank_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateEmailDomain',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(help_text='Domain part of the email address (e.g., synchronize.ru)', max_length=255, unique=True, verbose_name='Email domain')),
            ],
            options={
                'verbose_name': 'Corporate email domain',
                'verbose_name_plural': 'Corporate email domains',
                'ordering': ['domain'],
            },
        ),
    ]
